### ISSUE TITLE
Cancelamento de transações iOS

### ISSUE THREAD

**Issue by jgabrielfaria** [stone-payments/plugin-cordova#5]
Notei que o cancelamento de transação no iOS não está considerando o ID da venda, está pegando o primeiro objeto do array de transações da base do mPOS.

https://github.com/thehashlab/plugin-cordova/blob/master/src/ios/StoneSDK.m#L324

**Comment by jgabrielfaria** [comment]
No Android ele gera um "id" que está no formato `ID_AMOUNT_STATUS`, e ai para cancelar a venda ele usa apenas o `ID`: https://github.com/stone-payments/plugin-cordova/blob/master/src/android/StoneSDK.java#L209

**Comment by jgabrielfaria** [comment]
@victormendes5 @MarioDias17

**Comment by victormendes5** [comment]
@jgabrielfaria Te mandei uma mensagem no telegram, assim que vc puder, da uma olhada.
